# .travis.yml
language: node_js

node_js:
  - '8'
  - '10'
  - '12'

dist: trusty

after_script:
  - npm run-script coveralls

notifications:
  email: false

sudo: required

before_install:
  - docker-compose up -d
  - sh wait-databases.sh
