version: '2'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "13306:3306"
    environment:
      - TZ=UTC
      - MYSQL_ROOT_PASSWORD=mysqlrootpassword
      - MYSQL_DATABASE=dbmanger-test-database-deleteme
      - MYSQL_USER=knexdbmanagerdbowneruser
      - MYSQL_PASSWORD=knexdbmanagerdbowneruserpassword
